version: 2.1
jobs:
    run-test:
        description: 'Prettier, eslint & integration tests'
        environment:
            PG_USER: $PG_USER
            PG_DB: $PG_DB
        docker:
            - image: circleci/node:12
            - image: circleci/postgres:9.6-alpine-ram
              environment:
                  DATABASE_URL: postgresql://postgres@localhost:5432/circle_test
        steps:
            - checkout
            - run: yarn install --frozen-lockfile
            - run: yarn eslint
            - run: yarn prettier
            - run: dockerize -wait tcp://localhost:5432 -timeout 1m
            - run: timeout 60 yarn prisma migrate up --experimental
            - run: yarn test
    run-build:
        description: 'Build and push docker image to docker hub'
        docker:
            - image: cimg/base:2020.01
        steps:
            - checkout
            - setup_remote_docker
            - run: ./build.sh

workflows:
    build-and-test:
        jobs:
            - run-test
            - run-build:
                  requires:
                      - run-test
                  filters:
                      branches:
                          only: master
